#!/bin/bash

# RC files

# DEBUG=1

function x {
  if [ -n "$DEBUG" ]; then
    echo "$" "$@"
  else
    eval "$(printf '%q ' "$@")"
  fi
}

# Ensure directory exists
function xmkdir {
  if [ ! -d "$1" ]; then
    x mkdir -p "$1"
  fi
}

# Returns success if found
function exists {
  type -P "$1" > /dev/null
}

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in .*rc .gitconfig .gitignore_global; do
  if [ ! -L ~/$rc ]; then
    x ln -sfv $BASE/$rc ~/
  fi
done

for conf_dir in nvim; do
  if [ ! -L ~/.config/$conf_dir ]; then
    x ln -sfv $BASE/.config/$conf_dir ~/.config
  fi
done

for rc in tmuxinator; do
  if [ ! -L ~/.$rc  ]; then
    x ln -sfnvi $BASE/prv/$rc ~/.$rc
  fi
done

mkdir -p ~/.ssh/config.d/

for ssh_config in $BASE/prv/ssh/config.d/*; do
  if [ ! -L ~/.ssh/config.d/$(basename $ssh_config) ]; then
    x ln -sfnvi $ssh_config ~/.ssh/config.d/
  fi
done

mkdir -p ~/.mc/
curl -Ls https://raw.githubusercontent.com/peel/mc/master/solarized.ini > ~/.mc/solarized.ini

if exists code && ! exists codium; then
  DST=$HOME/.config/Code/User

  xmkdir "$DST"

  for f in "$BASE"/.config/Code/User/* ; do
    if [ ! -L "$DST/$(basename "$f")" ]; then
      x rm -rf "$DST/$(basename "$f")"
      x ln -sf "$f" "$DST"
    fi
  done
fi

if exists code-insiders; then
  DST="$HOME/.config/Code - Insiders/User"

  mkdir -p "$DST"

  for f in "$BASE"/.config/Code/User/* ; do
    if [ ! -L "$DST/$(basename "$f")" ]; then
      x rm -rf "$DST/$(basename "$f")"
      x ln -sf "$f" "$DST"
    fi
  done
fi

# if exists codium; then
#   DST=~/.config/VSCodium/User
#
#   xmkdir "$DST"
#
#   for f in "$BASE"/.config/Code/User/* ; do
#     if [ ! -L $DST/$(basename "$f") ]; then
#       x rm -rf "$DST/$(basename "$f")"
#       x ln -sf "$f" "$DST"
#     fi
#   done
# fi

DST=~/.local/share/applications
BASE_FILES="$BASE/.local/share/applications/*"

if [ -d $DST ] && [ -e $BASE_FILES ]; then  # checks if directory exists and files exist
  for f in $BASE_FILES ; do
    if [ ! -L "$DST/$(basename "$f")" ]; then
      x rm -rf "$DST/$(basename "$f")"
      # Without -s because KDE doesn't want to run .desktop file with executable permissions, and symlink has executable bit set
      x ln -f "$f" "$DST"
      x chmod a-x "$DST/$(basename "$f")"
    fi  
  done
else
  echo "[DEBUG] $DST does not exist or no files in $BASE/.local/share/applications/"
fi

