#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

# Install symlinks via stow

function install_with_stow() {
  echo "Running stow with $@"
  local stow_command="stow -v $@"
  $stow_command -n

  if [ $? -ne 0 ]; then
    echo "Error running stow command: $stow_command"
    exit 1
  fi

  read -p "Do you want to apply the changes? [y/N] " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    # echo "Applying changes..."
    $stow_command
  fi
}

install_with_stow -t $HOME --ignore .config/atuin/config.toml .
install_with_stow -t $HOME -d prv .

# Atuin keeps updating file so lets link it manually
mkdir -p ~/.config/atuin/
ln -sfn $BASE/.config/atuin/config.toml ~/.config/atuin/config.toml

# SSH
mkdir -p ~/.ssh/config.d/

for ssh_config in $BASE/prv/ssh/config.d/*; do
  if [ ! -L ~/.ssh/config.d/$(basename $ssh_config) ]; then
    x ln -sfnvi $ssh_config ~/.ssh/config.d/
  fi
done

# Midnight Commander
mkdir -p ~/.mc/
curl -Ls https://raw.githubusercontent.com/peel/mc/master/solarized.ini > ~/.mc/solarized.ini

# VIM

# export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload ~/.vim/undo ~/.vim/swapfiles ~/.vim/backupfiles
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall


echo "Would you like to add secret envs from vault ? [y/N]"
read -r response
if [[ $response =~ ^[Yy]$ ]]; then
  echo "Please provide your vault token"
  read -r VAULT_TOKEN

  # Fetch environment variables from Vault
  response=$(curl -s -H "X-Vault-Token: $VAULT_TOKEN" -X GET https://vault.8567153.xyz/v1/shell_envs/data/envs.zsh)

  # Check if the curl request was successful
  if [ $? -ne 0 ]; then
    echo "Failed to fetch data from Vault."
    exit 1
  fi

  # Process each key-value pair and save them to individual files
  echo "$response" | jq -r ".data.data | to_entries[] | \"export \(.key)=\(.value)\"" | while read -r line; do
    key=$(echo "$line" | cut -d'=' -f1 | sed 's/export //')
    echo "$line" > ~/.zshrc.d/envs.zsh
  done
fi
