.PHONY: setup setup-vim packages

all: packages setup setup-vim

define ZSH_PLUGINS_FILE_HEADER
#!/usr/bin/env zsh

# This file was generated by antibody (https://github.com/getantibody/antibody).
# Do not edit it directly but instead run "cd ~/dotfiles", update zsh_plugins.txt
# and then run "make plugins".

endef
export ZSH_PLUGINS_FILE_HEADER

setup:
	./install

setup-vim:
	./install-vim

packages:
	sudo apt-get install -y --no-install-recommends vim subversion silversearcher-ag tmux
