# Catppuccin Latte theme for Foot
# Source: https://github.com/catppuccin/foot

[colors]
foreground=4c4f69
background=ffffff

regular0=9ca0b0
regular1=d20f39
regular2=40a02b
regular3=df8e1d
regular4=1e66f5
regular5=ea76cb
regular6=179299
regular7=5c5f77

bright0=7c7f93
bright1=d20f39
bright2=40a02b
bright3=df8e1d
bright4=1e66f5
bright5=ea76cb
bright6=179299
bright7=6c6f85

dim0=9ca0b0
dim1=e64553
dim2=5ea851
dim3=e5a53a
dim4=4c84f7
dim5=f08fd5
dim6=2ea3aa
dim7=8c8fa1

selection-foreground=ffffff
selection-background=dc8a78

jump-labels=ffffff 1e66f5
urls=1e66f5
