name: Zsh Syntax Check

on:
  push:
    paths:
      - '.zshrc'
      - '.zsh/**'
  pull_request:
    paths:
      - '.zshrc'
      - '.zsh/**'

jobs:
  zsh-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Zsh syntax
        run: |
          set -e
          echo "zsh version: $(zsh --version)"
          files=(.zshrc $(find .zsh -name '*.zsh'))
          for f in "${files[@]}"; do
            echo "Checking $f"
            zsh -n "$f"
          done

